"$schema" = 'https://starship.rs/config-schema.json'

palette = 'custom'

# username root exicode git duration dotnet docker
format = """
[┏](pipe)\
$os\
$username\
$cmd_duration\
$status\
$container\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$dart\
$deno\
$dotnet\
$golang\
$java\
$gradle\
$lua\
$nim\
$nodejs\
$azure
[┖](pipe)$directory
[\\$](bright-cyan) """
continuation_prompt = '[>](bright-cyan) '

[palettes.custom]
pipe = '#767676'

[username]
format = '[\[](pipe)[$user]($style)[\]](pipe)'
show_always = true
style_root = "yellow bold"
style_user = "bright-cyan"

[directory]
format = '[\[](pipe)[$path]($style)[\]](pipe)'
truncate_to_repo = false
truncation_length = 16

[cmd_duration]
format = '[-\[](pipe)[󰔛 $duration](bright-cyan)[\]](pipe)'
min_time = 0
show_milliseconds = true

[status]
format = '[-\[](pipe)[x$common_meaning$signal_name$maybe_int]($style)[\]](pipe)'
disabled = false
map_symbol = true
pipestatus = true

[container]
format = '[-\[](pipe)[$symbol $name]($style)[\]](pipe)'
symbol = "⬢"

[git_branch]
format = '[-\[](pipe)[$symbol$branch(:$remote_branch)]($style)'
symbol = ' '

[git_state]
format = ' \([$state( $progress_current/$progress_total)]($style)\)'

[git_commit]
format = ' [\($hash$tag\)]($style)'
tag_symbol = '  '

[git_status]
format = ' ([$all_status$ahead_behind]($style))[\]](pipe)'
up_to_date = '≡'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[docker_context]
format = '[-\[](pipe)[$symbol $context]($style)[\]](pipe)'
symbol = ""

[dart]
format = '[-\[](pipe)[$symbol $version]($style)[\]](pipe)'
symbol = ""

[deno]
format = '[-\[](pipe)[$symbol $version]($style)[\]](pipe)'
symbol = ""

[dotnet]
format = '[-\[](pipe)[$symbol $version]($style)[\]](pipe)'
symbol = ""

[golang]
format = '[-\[](pipe)[$symbol $version]($style)[\]](pipe)'
symbol = ""

[java]
format = '[-\[](pipe)[$symbol $version]($style)[\]](pipe)'
symbol = ""

[gradle]
format = '[-\[](pipe)[$symbol $version]($style)[\]](pipe)'
symbol = ""

[lua]
format = '[-\[](pipe)[$symbol $version]($style)[\]](pipe)'
symbol = ""

[nim]
format = '[-\[](pipe)[$symbol $version]($style)[\]](pipe)'
symbol = "󰆥"

[nodejs]
format = '[-\[](pipe)[$symbol $version]($style)[\]](pipe)'
symbol = ""

[azure]
disabled = true
format = '[-\[](pipe)[$symbol $subscription]($style)[\]](pipe)'
symbol = "󰠅"

[os]
disabled = true
format = '[\[](pipe)[$symbol]($style)[\]](pipe)'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
